spring:
  redis:
    port: 6379
    host: 127.0.0.1
    database: 7
    jedis:
      pool:
        max-wait: 300ms
        max-active: 1000
  datasource:
    url: jdbc:mysql://localhost:3306/pet?useUnicode=true
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    #数据表的创建方式,none则不使用
    hibernate:
      ddl-auto: none
    #显示操作的sql语句
    show-sql: true


server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  #servlet:
    #context-path: /pet
